language: go

services:
  - docker

go:
- "1.11.x"

before_install:
- export GO111MODULE=on && go mod download
- docker pull rabbitmq:3.7.4
- docker run -p 5672:5672 -e RABBITMQ_DEFAULT_USER="user" -e RABBITMQ_DEFAULT_PASS="pass" -d --restart always --name ci_rabbitmq rabbitmq:3.7.4

script:
- go test -race -v ./...
- cd pkg && cd rabbitmq
- go test -integration=true integration_test.go
- cd .. && cd ..
- go build

after_script:
  - docker stop ci_rabbitmq
  - docker rm ci_rabbitmq

after_success:
  - chmod +x ./hack/docker_build.sh
  - ./hack/docker_build.sh