language: go

services:
  - docker

go:
- "1.13.x"

before_install:
- export GO111MODULE=on && go mod download
- docker pull rabbitmq:3.7.4
- docker run -p 5672:5672 -e RABBITMQ_DEFAULT_USER="user" -e RABBITMQ_DEFAULT_PASS="pass" -d --restart always --name ci_rabbitmq rabbitmq:3.7.4
- go get golang.org/x/lint/golint

script:
- golint ./...
- go test -race ./...
- go test -coverprofile=coverage.txt -covermode=atomic -v ./...
- go build
- docker build --rm -t ci:latest .

after_script:
  - docker stop ci_rabbitmq
  - docker rm ci_rabbitmq
  - docker rmi ci:latest

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - chmod +x ./hack/docker_build.sh
  - ./hack/docker_build.sh