[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  branch = "master"
  name = "github.com/streadway/amqp"

[[constraint]]
  name = "github.com/openfaas/faas"
  version = "0.9.11"

[[constraint]]
  name = "github.com/docker/docker"
  packages = [
      "pkg/namesgenerator",
      "pkg/random",
  ]
  version = "v1.13.1"