version: '3.2'
services:
  rabbitqueue:
    image: rabbitmq:3.7.4
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    ports:
      - "5672:5672"
    networks:
      - streaming


networks:
  streaming:

