version: '3.2'
services:
  rabbitqueue:
    image: rabbitmq:3.7.4
    hostname: rabbitqueue
    enviroment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    networks:
      - streaming

  connector:
    image: alexellis2/kafka-connector:latest
    hostname: kafka-connector
    environment:
      gateway_url: http://gateway:8080
      topics: "faas-request,"
    networks:
      - streaming
      - func_functions

networks:
  streaming:
    driver: overlay
    attachable: true
  func_functions:
    external: true
