version: '3.2'
services:
  connector:
    image: alexellis2/kafka-connector:latest
    hostname: kafka-connector
    environment:
      gateway_url: http://gateway:8080
      topics: "faas-request,"
    networks:
      - streaming
      - func_functions

networks:
  streaming:
    driver: overlay
    attachable: true
  func_functions:
    external: true
