name: "CI"

on:
  push:
    branches: [develop, v0, v1]

  pull_request:
    branches: [develop]

  workflow_dispatch:

jobs:
  scan:
    name: Analyse
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: ["go"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2
      # If this run was triggered by a pull request event, then checkout
      # the head of the pull request instead of the merge commit.
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.20.0
          cache: false

      - name: Build
        run: go build -v ./...

      - name: Test for Race Conditions
        run: go test -race ./...

      - name: Test with Coverage
        run: go test -coverprofile=coverage.txt -covermode=atomic -v ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.txt
          flags: unit-tests
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.51.1
          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
