name: "CI"

on:
  push:
    branches: [develop, master]
    
  pull_request:
    branches: [ develop ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 2
    # If this run was triggered by a pull request event, then checkout
    # the head of the pull request instead of the merge commit.
    - run: git checkout HEAD^2
      if: ${{ github.event_name == 'pull_request' }}

    # Should hopefully give enough time for it to start prior to testing
    - name: Start RabbitMQ
      uses: getong/rabbitmq-action@v1.2
      with:
        rabbitmq version: '3.8.11'
        host port: 5672
        rabbitmq user: 'user'
        rabbitmq password: 'pass'
      
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...
    
    - name: Test for Race Conditions
      run: go test -race ./...

    - name: Test with Coverage
      run: go test -coverprofile=coverage.txt -covermode=atomic -v ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.txt
        flags: unit-tests
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true
  
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
        version: v1.29
        # Optional: show only new issues if it's a pull request. The default value is `false`.
        only-new-issues: true