apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-connector-configmap
data:
  OPEN_FAAS_GW_URL: "http://gateway.openfaas:8080"
  PATH_TO_TOPOLOGY: "."
  RMQ_HOST: "replace_me"
  RMQ_PORT: "replace_me"
  RMQ_USER: "replace_me"
  RMQ_PASS: "replace_me"
  REQ_TIMEOUT: "30s"
  TOPIC_MAP_REFRESH_TIME: "30s"
  RMQ_TOPOLOGY: |
    - name: AEx
      topics: [Foo, Bar]
      declare: true
      type: "direct"
      durable: false
      auto-deleted: false
    - name: BEx
      topics: [Dead, Beef]
      declare: false