apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-connector
  namespace: openfaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-connector
  template:
    metadata:
      labels:
        app: rabbitmq-connector
    spec:
      containers:
      - name: connector
        image: templum/rabbitmq-connector:develop
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: rabbitmq-connector-configmap
        resources: # Adjust them to suite your needs
          requests:
            memory: 512Mi
            cpu: 1
          limits:
            memory: 1024Mi
            cpu: 2
        volumeMounts:
          - name: gateway-basic-auth
            readOnly: true
            mountPath: "/etc/openfaas"
      volumes:
        - name: gateway-basic-auth
          secret:
            secretName: gateway-basic-auth
