version: '3.3'
services:
  rabbitqueue:
    image: rabbitmq:3.7.4
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    ports:
      - "5672:5672"
    networks:
      - streaming

  producer:
    image: templum/sample-producer:latest
    environment:
      RMQ_HOST: "rabbitqueue"
      RMQ_PORT: "5672"
      RMQ_USER: "user"
      RMQ_PASS: "pass"
    networks:
      - streaming

  connector:
    image: templum/rabbitmq-connector:dev
    environment:
      RMQ_TOPICS: "billing,account"
      RMQ_HOST: "rabbitqueue"
      RMQ_PORT: "5672"
      RMQ_USER: "user"
      RMQ_PASS: "pass"
      OPEN_FAAS_GW_URL: "http://gateway:8080"
      basic_auth: "true"
      secret_mount_path: "/run/secrets/"
    networks:
      - func_functions
      - streaming
    secrets:
      - basic-auth-user
      - basic-auth-password

networks:
  streaming:
    driver: overlay
    attachable: true
  func_functions:
    external: true

secrets:
  basic-auth-user:
    external: true
  basic-auth-password:
    external: true

